/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoandru;

import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author andru
 */
public class InicioX extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    menu main;
    String rutaImagenes = "images/"; 
    ImageIcon imagenHombre = new ImageIcon(rutaImagenes + "hombre.png");
    ImageIcon imagenMujer = new ImageIcon(rutaImagenes + "mujer.png");
    
    public InicioX(menu main) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.main=main;
        
      if(main.gu.Logged().getGenero().equalsIgnoreCase("Masculino")){
          imagenh.setIcon(imagenHombre);
       } else if (main.gu.Logged().getGenero().equalsIgnoreCase("Femenino")){
          imagenh.setIcon(imagenMujer);
       }
        
       arroba.setText("@"+main.gu.Logged().getNick());
       String search = searchhashtag.getText(); 
DefaultListModel<String> model = new DefaultListModel<>();
listahashtag.setModel(model);  

tweets[] arregloTweets = main.gt.obtenerTweets(); 

for (int i = 0; i < arregloTweets.length; i++) {
    tweets tweet = arregloTweets[i]; // Obtener cada tweet del arreglo
    if (tweet != null && tweet.getTweet().contains("@" + search)) {
        model.addElement(tweet.getUser() + ": " + tweet.getTweet()); // Agregar a la lista si contiene el hashtag
    }
}

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchhashtag = new javax.swing.JTextField();
        botonsearch = new javax.swing.JButton();
        imagenh = new javax.swing.JLabel();
        publicacion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttt = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        editarprofile = new javax.swing.JButton();
        cerrarsesion = new javax.swing.JButton();
        arroba = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listahashtag = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        menciones = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        searchhashtag.setBackground(new java.awt.Color(0, 0, 0));
        searchhashtag.setForeground(new java.awt.Color(153, 255, 255));
        searchhashtag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchhashtagActionPerformed(evt);
            }
        });

        botonsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaso.png"))); // NOI18N
        botonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsearchActionPerformed(evt);
            }
        });

        imagenh.setBackground(new java.awt.Color(204, 204, 204));
        imagenh.setForeground(new java.awt.Color(255, 255, 255));
        imagenh.setText("jLabel2");

        publicacion.setBackground(new java.awt.Color(0, 0, 0));
        publicacion.setForeground(new java.awt.Color(255, 255, 255));
        publicacion.setText("Que estas pensando...?");
        publicacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        publicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                publicacionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                publicacionMouseExited(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Publicar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ttt.setBackground(new java.awt.Color(0, 0, 0));
        ttt.setColumns(20);
        ttt.setForeground(new java.awt.Color(255, 255, 255));
        ttt.setRows(5);
        jScrollPane1.setViewportView(ttt);

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("PERFIL");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        editarprofile.setBackground(new java.awt.Color(0, 0, 51));
        editarprofile.setForeground(new java.awt.Color(0, 204, 255));
        editarprofile.setText("CONFIGURACION");
        editarprofile.setBorder(null);
        editarprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarprofileActionPerformed(evt);
            }
        });

        cerrarsesion.setBackground(new java.awt.Color(0, 0, 51));
        cerrarsesion.setForeground(new java.awt.Color(0, 153, 204));
        cerrarsesion.setText("Cerrar Sesion");
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });

        arroba.setForeground(new java.awt.Color(255, 255, 255));
        arroba.setText("@");

        jScrollPane3.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        listahashtag.setBackground(new java.awt.Color(0, 0, 0));
        listahashtag.setForeground(new java.awt.Color(255, 255, 255));
        listahashtag.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listahashtag);

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        menciones.setBackground(new java.awt.Color(0, 0, 0));
        menciones.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(menciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(cerrarsesion))
                            .addComponent(imagenh, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editarprofile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(arroba, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(publicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(searchhashtag, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchhashtag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))
                            .addComponent(botonsearch))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane2)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imagenh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arroba, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                        .addComponent(cerrarsesion)
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchhashtagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchhashtagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchhashtagActionPerformed

    private void botonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsearchActionPerformed
    
    String search = searchhashtag.getText(); 
DefaultListModel<String> model = new DefaultListModel<>();
listahashtag.setModel(model);  

tweets[] arregloTweets = main.gt.obtenerTweets(); 

for (int i = 0; i < arregloTweets.length; i++) {
    tweets tweet = arregloTweets[i]; // Obtener cada tweet del arreglo
    if (tweet != null && tweet.getTweet().contains("#" + search)) {
        model.addElement(tweet.getUser() + ": " + tweet.getTweet()); // Agregar a la lista si contiene el hashtag
    }
}

if (model.isEmpty()) {
    JOptionPane.showMessageDialog(null, "No se encontraron tweets con el hashtag #" + search);
}
        
        
  
  



        // TODO add your handling code here:
    }//GEN-LAST:event_botonsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String p = publicacion.getText();
String t = ttt.getText();

if(p.length()<=140){
    main.gt.agregarTweet(main.gu.Logged().getNick(), p, main.gu.FechaActual());
ttt.setText(main.gu.Logged().getNick()+"\n"+p+"\n                                                                                               "+main.gu.FechaActual()+"\n-----------------------------------------------------------------------------------------------------------------------------\n"+t);
publicacion.setText("Que estas pensando...?");
}
else{
    JOptionPane.showMessageDialog(null,"Solo se permiten 140 caracteres, cantidad actual:"+p.length());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void publicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publicacionMouseClicked
String p= publicacion.getText();
        if(p.equalsIgnoreCase("Que estas pensando...?"))
        publicacion.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_publicacionMouseClicked

    private void publicacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publicacionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_publicacionMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 new Perfil(main).setVisible(true);
             this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
       main.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_cerrarsesionActionPerformed

    private void editarprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarprofileActionPerformed
      
    }//GEN-LAST:event_editarprofileActionPerformed

    /**
     * @param args the command line arguments
     */
    
  
     
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arroba;
    private javax.swing.JButton botonsearch;
    private javax.swing.JButton cerrarsesion;
    private javax.swing.JButton editarprofile;
    private javax.swing.JLabel imagenh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listahashtag;
    private javax.swing.JList<String> menciones;
    private javax.swing.JTextField publicacion;
    private javax.swing.JTextField searchhashtag;
    private javax.swing.JTextArea ttt;
    // End of variables declaration//GEN-END:variables
}
