


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoandru;

/**
 *
 * @author HP
 */
public class PerfilUser1 extends javax.swing.JFrame {

    /**
     * Creates new form PerfilUser1
     */
    menu main;
    private String xy;
    public PerfilUser1(menu main) {
        initComponents();
        this.main=main;
        arroba.setText("@" + main.gu.returnPerfil());
        
        
        
            if(main.usu.fling.buscar(main.gu.Busqueda(main.gu.returnPerfil()))==true){

            ttt.setText(main.gu.Busqueda(main.gu.returnPerfil())+"\nNombre: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getNombreUsuario()
                +"\nApodo: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getNick()
                +"\nGenero: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getGenero()
                +"\nEdad: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getEdad()
                +"\nFecha de Ingreso: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getFechaCreacion()+"\nLo sigues");
            followMod.setText("Dejar de Seguir");

        }else if(main.usu.fling.buscar(main.gu.Busqueda(main.gu.returnPerfil()))==false){

            ttt.setText(main.gu.Busqueda(main.gu.returnPerfil())+"\nNombre: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getNombreUsuario()
                +"\nApodo: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getNick()
                +"\nGenero: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getGenero()
                +"\nEdad: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getEdad()
                +"\nFecha de Ingreso: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getFechaCreacion()+"\nNo lo sigues");
            followMod.setText("Seguir");

        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonsearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        REGRESAR = new javax.swing.JButton();
        followMod = new javax.swing.JButton();
        arroba = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        botonsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaso.png"))); // NOI18N
        botonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsearchActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hombre (1).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        REGRESAR.setBackground(new java.awt.Color(0, 0, 51));
        REGRESAR.setForeground(new java.awt.Color(0, 153, 204));
        REGRESAR.setText("REGRESAR");
        REGRESAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REGRESARMouseClicked(evt);
            }
        });
        REGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGRESARActionPerformed(evt);
            }
        });

        followMod.setBackground(new java.awt.Color(0, 0, 51));
        followMod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        followMod.setForeground(new java.awt.Color(0, 204, 255));
        followMod.setText("Seguir");
        followMod.setBorder(null);
        followMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followModActionPerformed(evt);
            }
        });

        arroba.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        arroba.setForeground(new java.awt.Color(255, 255, 255));

        ttt.setColumns(20);
        ttt.setRows(5);
        jScrollPane1.setViewportView(ttt);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(REGRESAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(followMod, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(arroba, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(arroba, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(botonsearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(followMod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REGRESAR))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsearchActionPerformed

        if(main.usu.fling.buscar(main.gu.Busqueda(main.gu.returnPerfil()))==true){

            ttt.setText(main.gu.Busqueda(main.gu.returnPerfil())+"\nNombre: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getNombreUsuario()
                +"\nApodo: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getNick()
                +"\nGenero: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getGenero()
                +"\nEdad: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getEdad()
                +"\nFecha de Ingreso: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getFechaCreacion()+"\nLo sigues");
            followMod.setText("Dejar de Seguir");

        }else if(main.usu.fling.buscar(main.gu.Busqueda(main.gu.returnPerfil()))==false){

            ttt.setText(main.gu.Busqueda(main.gu.returnPerfil())+"\nNombre: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getNombreUsuario()
                +"\nApodo: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getNick()
                +"\nGenero: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getGenero()
                +"\nEdad: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getEdad()
                +"\nFecha de Ingreso: "+main.gu.BuscarUsuario(main.gu.Busqueda(main.gu.returnPerfil())).getFechaCreacion()+"\nNo lo sigues");
            followMod.setText("Seguir");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_botonsearchActionPerformed

    private void REGRESARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGRESARMouseClicked
        new Perfil(main).setVisible(true);

        this.dispose();
    }//GEN-LAST:event_REGRESARMouseClicked

    private void REGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGRESARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGRESARActionPerformed

    private void followModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followModActionPerformed
        
        if(followMod.getText()=="Seguir" && !main.gu.Logged().getNick().equalsIgnoreCase(main.gu.returnPerfil())){
            if(main.gu.lastUserLogged(main.gu.Logged()).getNick().equalsIgnoreCase(xy)){
            main.usu.AgregarFollowing(main.gu.returnPerfil());
            }
            if(main.gu.Logged().getNick().equalsIgnoreCase(xy)){
            main.usu.fl.AgregarFollower(main.gu.Logged().getNick());
            }
            
        }else if(followMod.getText()=="Dejar de Seguir" && !main.gu.Logged().getNick().equalsIgnoreCase(main.gu.returnPerfil())){
             if(main.gu.lastUserLogged(main.gu.Logged()).getNick().equalsIgnoreCase(xy)){
            main.usu.DejarFollow(main.gu.returnPerfil());
             }
             if(main.gu.Logged().getNick().equalsIgnoreCase(xy)){
            main.usu.fl.followerLost(main.gu.Logged().getNick());
             }
        }
        
        main.gu.lastUserLogged(main.gu.Logged());
        xy=main.gu.returnPerfil();
        
    }//GEN-LAST:event_followModActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton REGRESAR;
    private javax.swing.JLabel arroba;
    private javax.swing.JButton botonsearch;
    private javax.swing.JButton followMod;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ttt;
    // End of variables declaration//GEN-END:variables
}
