/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoandru;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Perfil extends javax.swing.JFrame {

    /**
     * Creates new form Perfil
     */
    menu main;
    boolean followmod;
    String usuarios="";
    String usernick;
    public Perfil(menu main) {
        initComponents();
        this.main=main;
        arroba.setText("@"+main.gu.Logged().getNick());
        
        
            
        
        
         seguidores.setText("\nSeguidores: "+main.usu.fl.getfollowers());
       seguidos.setText("\nSeguidos: "+main.usu.fling.getfollowing());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonsearch = new javax.swing.JButton();
        publicacion = new javax.swing.JTextField();
        buscarPersonas = new javax.swing.JButton();
        REGRESAR = new javax.swing.JButton();
        arroba = new javax.swing.JLabel();
        desactivarCuenta = new javax.swing.JButton();
        entrarPerfil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttt = new javax.swing.JTextArea();
        seguidores = new javax.swing.JLabel();
        seguidos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        botonsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vaso.png"))); // NOI18N
        botonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsearchActionPerformed(evt);
            }
        });

        publicacion.setBackground(new java.awt.Color(0, 0, 51));
        publicacion.setForeground(new java.awt.Color(255, 255, 255));
        publicacion.setText("A quien buscas...?");
        publicacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        publicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                publicacionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                publicacionMouseExited(evt);
            }
        });
        publicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicacionActionPerformed(evt);
            }
        });

        buscarPersonas.setBackground(new java.awt.Color(0, 0, 51));
        buscarPersonas.setForeground(new java.awt.Color(0, 204, 255));
        buscarPersonas.setText("Editar Perfil");
        buscarPersonas.setBorder(null);
        buscarPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPersonasActionPerformed(evt);
            }
        });

        REGRESAR.setBackground(new java.awt.Color(0, 0, 51));
        REGRESAR.setForeground(new java.awt.Color(0, 153, 204));
        REGRESAR.setText("REGRESAR");
        REGRESAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                REGRESARMouseClicked(evt);
            }
        });
        REGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGRESARActionPerformed(evt);
            }
        });

        arroba.setForeground(new java.awt.Color(255, 255, 255));
        arroba.setText("@");

        desactivarCuenta.setBackground(new java.awt.Color(0, 0, 51));
        desactivarCuenta.setForeground(new java.awt.Color(0, 204, 255));
        desactivarCuenta.setText("DESACTIVAR CUE.");
        desactivarCuenta.setBorder(null);
        desactivarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactivarCuentaActionPerformed(evt);
            }
        });

        entrarPerfil.setBackground(new java.awt.Color(0, 0, 51));
        entrarPerfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        entrarPerfil.setForeground(new java.awt.Color(0, 204, 255));
        entrarPerfil.setText("Entrar al Perfil");
        entrarPerfil.setBorder(null);
        entrarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarPerfilActionPerformed(evt);
            }
        });

        ttt.setColumns(20);
        ttt.setRows(5);
        jScrollPane1.setViewportView(ttt);

        seguidores.setForeground(new java.awt.Color(255, 255, 255));
        seguidores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seguidores.setToolTipText("");
        seguidores.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        seguidos.setForeground(new java.awt.Color(255, 255, 255));
        seguidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seguidos.setToolTipText("");
        seguidos.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(REGRESAR))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(arroba, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(desactivarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(266, 266, 266)
                        .addComponent(buscarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seguidos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(publicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 304, Short.MAX_VALUE)
                .addComponent(entrarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(273, 273, 273))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(arroba, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonsearch)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(buscarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(seguidores, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seguidos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(desactivarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(REGRESAR)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsearchActionPerformed
       
       usernick = publicacion.getText(); 
        
          if(main.usu.fling.buscar(main.gu.Busqueda(usernick))==true) {
         ttt.setText(main.gu.Busqueda(usernick)+"\nLo sigues");
         entrarPerfil.setText("Entrar Perfil");
         main.gu.perfilUser(usernick);
         
          }else if(main.usu.fling.buscar(main.gu.Busqueda(usernick))==false){
              ttt.setText(main.gu.Busqueda(usernick)+"\nNo lo sigues");
         entrarPerfil.setText("Entrar Perfil");
         main.gu.perfilUser(usernick);
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_botonsearchActionPerformed

    private void publicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publicacionMouseClicked
        String p= publicacion.getText();
        if(p.equalsIgnoreCase("A quien buscas...?"))
        publicacion.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_publicacionMouseClicked

    private void publicacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publicacionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_publicacionMouseExited

    private void REGRESARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_REGRESARMouseClicked
        new InicioX(main).setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_REGRESARMouseClicked

    private void REGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGRESARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_REGRESARActionPerformed

    private void publicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publicacionActionPerformed

    private void buscarPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPersonasActionPerformed
    }//GEN-LAST:event_buscarPersonasActionPerformed

    private void entrarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarPerfilActionPerformed
        
         new PerfilUser1(main).setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_entrarPerfilActionPerformed

    private void desactivarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactivarCuentaActionPerformed
  
        main.gu.desactivarCuenta(main.gu.Logged().getNick());
               main.setVisible(true);
               this.dispose();
        
        
        
    }//GEN-LAST:event_desactivarCuentaActionPerformed

    /**
     * @param args the command line argument
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton REGRESAR;
    private javax.swing.JLabel arroba;
    private javax.swing.JButton botonsearch;
    private javax.swing.JButton buscarPersonas;
    private javax.swing.JButton desactivarCuenta;
    private javax.swing.JButton entrarPerfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField publicacion;
    private javax.swing.JLabel seguidores;
    private javax.swing.JLabel seguidos;
    private javax.swing.JTextArea ttt;
    // End of variables declaration//GEN-END:variables
}